### ISSUE TITLE
Node16 cookbook tests just started failing in CI (monkeypatch race condition?)

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#1882]
I just saw the failure below in #1881, and only in Node 16 CI tests.  #1881 is a spec-change-only PR so obviously it didn't cause the problem. I assume something changed in Node itself that's causing our monkeypatching of the `Date` object to fail. Perhaps some kind of race condition?

```
file:///home/runner/work/proposal-temporal/proposal-temporal/docs/cookbook/instantFromLegacyDate.mjs:2
const instant = legacyDate.toTemporalInstant();
                           ^

TypeError: legacyDate.toTemporalInstant is not a function
    at file:///home/runner/work/proposal-temporal/proposal-temporal/docs/cookbook/instantFromLegacyDate.mjs:2:28
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
Error: Process completed with exit code 1.
```
